//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Inputs/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""MenuMando"",
            ""id"": ""3ac64137-016f-4848-9f5b-eb8155c6cdc8"",
            ""actions"": [
                {
                    ""name"": ""Selection"",
                    ""type"": ""Button"",
                    ""id"": ""9c96a05b-08a0-4c00-9c46-f845c39d7837"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mov"",
                    ""type"": ""Value"",
                    ""id"": ""6360090c-d155-453e-9ce9-ec8af50c5786"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""f8e09518-369d-408a-af7a-415866f25407"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24092e33-b2c2-456e-93c1-ac79136bd3b9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""direction"",
                    ""id"": ""bd4975f1-b4a7-434e-ab80-6d7bd4ef599b"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mov"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""205dca29-9ab5-45af-8f6a-48a5f6a6818a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""bf1b55c3-4f2e-4f57-8216-d7b87dc1c102"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""592e6398-007e-492d-bbaf-3b60f9373fb6"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""72691cc6-d249-4f9b-8633-1eff86f78ef8"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b99f0413-4e4e-4e97-98ad-f55b9258210a"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuTeclado"",
            ""id"": ""e3b2b234-dc61-4bb1-b7d6-adee88cc0a0a"",
            ""actions"": [
                {
                    ""name"": ""Selection"",
                    ""type"": ""Button"",
                    ""id"": ""a34e94e3-b39a-41b2-82b0-8aa18d46f26e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mov"",
                    ""type"": ""Value"",
                    ""id"": ""c24c83b4-0dcc-4ff8-abb1-2bbe042c4524"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""b4707fc4-4753-4b20-902d-785962d0850f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""direction"",
                    ""id"": ""fe219083-9a69-4d7e-9a05-7ce9681d000f"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mov"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""5b3a43b1-e939-491d-8c3c-af8e73ebd085"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""30029d54-ba1c-410c-b1e2-268d79129803"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3cddf268-0bad-4593-80c0-e11f3f87853d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d65693f9-fbd5-404e-ab3a-da7de5c76259"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""090d99b2-36d4-4638-b3c9-f1eb3b582a6d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a092b76-2c62-4a89-85a8-21624bcaef91"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GamePlay"",
            ""id"": ""3654572c-75ff-49ab-9f5a-e42abccd4074"",
            ""actions"": [
                {
                    ""name"": ""MovePc"",
                    ""type"": ""Button"",
                    ""id"": ""a01119bb-5d2c-403c-9d0c-82313a2d9d7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionsPC"",
                    ""type"": ""Button"",
                    ""id"": ""f9d6348c-bb62-4377-8035-4735f21d1968"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5ea70ffb-5a4b-4d61-bdea-ec186cf3c998"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7dc47e1-f9b4-465a-8b85-80d8d0b2795a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d516cce0-09ff-4266-8d89-5bb2609442d2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6a6bb40-c902-44dc-ac2b-8d298ffe6244"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a05c05f8-c22c-4c6f-a1c5-54a7bd03a2e6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionsPC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        },
        {
            ""name"": ""GamePad"",
            ""bindingGroup"": ""GamePad"",
            ""devices"": []
        }
    ]
}");
        // MenuMando
        m_MenuMando = asset.FindActionMap("MenuMando", throwIfNotFound: true);
        m_MenuMando_Selection = m_MenuMando.FindAction("Selection", throwIfNotFound: true);
        m_MenuMando_Mov = m_MenuMando.FindAction("Mov", throwIfNotFound: true);
        m_MenuMando_Start = m_MenuMando.FindAction("Start", throwIfNotFound: true);
        // MenuTeclado
        m_MenuTeclado = asset.FindActionMap("MenuTeclado", throwIfNotFound: true);
        m_MenuTeclado_Selection = m_MenuTeclado.FindAction("Selection", throwIfNotFound: true);
        m_MenuTeclado_Mov = m_MenuTeclado.FindAction("Mov", throwIfNotFound: true);
        m_MenuTeclado_Start = m_MenuTeclado.FindAction("Start", throwIfNotFound: true);
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_MovePc = m_GamePlay.FindAction("MovePc", throwIfNotFound: true);
        m_GamePlay_ActionsPC = m_GamePlay.FindAction("ActionsPC", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MenuMando
    private readonly InputActionMap m_MenuMando;
    private List<IMenuMandoActions> m_MenuMandoActionsCallbackInterfaces = new List<IMenuMandoActions>();
    private readonly InputAction m_MenuMando_Selection;
    private readonly InputAction m_MenuMando_Mov;
    private readonly InputAction m_MenuMando_Start;
    public struct MenuMandoActions
    {
        private @Inputs m_Wrapper;
        public MenuMandoActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Selection => m_Wrapper.m_MenuMando_Selection;
        public InputAction @Mov => m_Wrapper.m_MenuMando_Mov;
        public InputAction @Start => m_Wrapper.m_MenuMando_Start;
        public InputActionMap Get() { return m_Wrapper.m_MenuMando; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuMandoActions set) { return set.Get(); }
        public void AddCallbacks(IMenuMandoActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuMandoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuMandoActionsCallbackInterfaces.Add(instance);
            @Selection.started += instance.OnSelection;
            @Selection.performed += instance.OnSelection;
            @Selection.canceled += instance.OnSelection;
            @Mov.started += instance.OnMov;
            @Mov.performed += instance.OnMov;
            @Mov.canceled += instance.OnMov;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
        }

        private void UnregisterCallbacks(IMenuMandoActions instance)
        {
            @Selection.started -= instance.OnSelection;
            @Selection.performed -= instance.OnSelection;
            @Selection.canceled -= instance.OnSelection;
            @Mov.started -= instance.OnMov;
            @Mov.performed -= instance.OnMov;
            @Mov.canceled -= instance.OnMov;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
        }

        public void RemoveCallbacks(IMenuMandoActions instance)
        {
            if (m_Wrapper.m_MenuMandoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuMandoActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuMandoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuMandoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuMandoActions @MenuMando => new MenuMandoActions(this);

    // MenuTeclado
    private readonly InputActionMap m_MenuTeclado;
    private List<IMenuTecladoActions> m_MenuTecladoActionsCallbackInterfaces = new List<IMenuTecladoActions>();
    private readonly InputAction m_MenuTeclado_Selection;
    private readonly InputAction m_MenuTeclado_Mov;
    private readonly InputAction m_MenuTeclado_Start;
    public struct MenuTecladoActions
    {
        private @Inputs m_Wrapper;
        public MenuTecladoActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Selection => m_Wrapper.m_MenuTeclado_Selection;
        public InputAction @Mov => m_Wrapper.m_MenuTeclado_Mov;
        public InputAction @Start => m_Wrapper.m_MenuTeclado_Start;
        public InputActionMap Get() { return m_Wrapper.m_MenuTeclado; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuTecladoActions set) { return set.Get(); }
        public void AddCallbacks(IMenuTecladoActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuTecladoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuTecladoActionsCallbackInterfaces.Add(instance);
            @Selection.started += instance.OnSelection;
            @Selection.performed += instance.OnSelection;
            @Selection.canceled += instance.OnSelection;
            @Mov.started += instance.OnMov;
            @Mov.performed += instance.OnMov;
            @Mov.canceled += instance.OnMov;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
        }

        private void UnregisterCallbacks(IMenuTecladoActions instance)
        {
            @Selection.started -= instance.OnSelection;
            @Selection.performed -= instance.OnSelection;
            @Selection.canceled -= instance.OnSelection;
            @Mov.started -= instance.OnMov;
            @Mov.performed -= instance.OnMov;
            @Mov.canceled -= instance.OnMov;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
        }

        public void RemoveCallbacks(IMenuTecladoActions instance)
        {
            if (m_Wrapper.m_MenuTecladoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuTecladoActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuTecladoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuTecladoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuTecladoActions @MenuTeclado => new MenuTecladoActions(this);

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private List<IGamePlayActions> m_GamePlayActionsCallbackInterfaces = new List<IGamePlayActions>();
    private readonly InputAction m_GamePlay_MovePc;
    private readonly InputAction m_GamePlay_ActionsPC;
    public struct GamePlayActions
    {
        private @Inputs m_Wrapper;
        public GamePlayActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePc => m_Wrapper.m_GamePlay_MovePc;
        public InputAction @ActionsPC => m_Wrapper.m_GamePlay_ActionsPC;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void AddCallbacks(IGamePlayActions instance)
        {
            if (instance == null || m_Wrapper.m_GamePlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Add(instance);
            @MovePc.started += instance.OnMovePc;
            @MovePc.performed += instance.OnMovePc;
            @MovePc.canceled += instance.OnMovePc;
            @ActionsPC.started += instance.OnActionsPC;
            @ActionsPC.performed += instance.OnActionsPC;
            @ActionsPC.canceled += instance.OnActionsPC;
        }

        private void UnregisterCallbacks(IGamePlayActions instance)
        {
            @MovePc.started -= instance.OnMovePc;
            @MovePc.performed -= instance.OnMovePc;
            @MovePc.canceled -= instance.OnMovePc;
            @ActionsPC.started -= instance.OnActionsPC;
            @ActionsPC.performed -= instance.OnActionsPC;
            @ActionsPC.canceled -= instance.OnActionsPC;
        }

        public void RemoveCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamePlayActions instance)
        {
            foreach (var item in m_Wrapper.m_GamePlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamePadSchemeIndex = -1;
    public InputControlScheme GamePadScheme
    {
        get
        {
            if (m_GamePadSchemeIndex == -1) m_GamePadSchemeIndex = asset.FindControlSchemeIndex("GamePad");
            return asset.controlSchemes[m_GamePadSchemeIndex];
        }
    }
    public interface IMenuMandoActions
    {
        void OnSelection(InputAction.CallbackContext context);
        void OnMov(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
    }
    public interface IMenuTecladoActions
    {
        void OnSelection(InputAction.CallbackContext context);
        void OnMov(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
    }
    public interface IGamePlayActions
    {
        void OnMovePc(InputAction.CallbackContext context);
        void OnActionsPC(InputAction.CallbackContext context);
    }
}
